[package]
name = "scuttlebutt-attack"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssb-crypto = { version = "0.2.2", default-features = false, features = ["dalek"] }
ssb-handshake = { path = "deps/ssb-handshake", default-features = false }
genio = { version = "0.2.1", default-features = false }
rand = { version = "0.7.3", default_features = false }
rand_chacha = { version = "0.2.2" }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"

[patch.crates-io]
curve25519-dalek = { path = "deps/curve25519-dalek/" }
